apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "socialnetworkreact.fullname" . }}
  labels:
    app: {{ template "socialnetworkreact.name" . }}
    chart: {{ template "socialnetworkreact.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "socialnetworkreact.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "socialnetworkreact.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.socialnetworkreact.image }}:{{ .Values.socialnetworkreact.tag }}"
          imagePullPolicy: {{ .Values.socialnetworkreact.pullPolicy }}
          env:
          {{- range $key, $value := .Values.socialnetworkreact.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.url }}
              port: {{ .Values.healthcheck.port }}
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.url }}
              port: {{ .Values.healthcheck.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
